steps:

- name: 'gcr.io/concrete-crow-244606/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=http://35.208.215.165:9000'
    - '-Dsonar.login=853eb32d94a99613ba41174803fa057be4dd8420'
    - '-Dsonar.projectKey=javademoapp'
    - '-Dsonar.sources=./src/user/'
  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/concrete-crow-244606/javademoappwithcloudbuild', '.']
    
images: ['gcr.io/concrete-crow-244606/javademoappwithcloudbuild']
